### ISSUE TITLE
Big-IP

### ISSUE THREAD

**Issue by nlaha** [ajmwagar/powerschool_gradecheck#1]
It looks like the SPS powerschool login is going through a sort of load balancer proxy shit, that's why you were getting the 302 redirect. basically, we are getting positive authentication but we can't go further than that. I don't think its an error in your code, I think we just have to figure out a workaround.

More info on Big-IP:
https://f5.com/products/big-ip

**Comment by ajmwagar** [comment]
Big IP was the blocking software. We need to bypass this aswell.

**Comment by nlaha** [comment]
hmm, yeah, so its a blocker, but also a load balancer to speed up the connection. The question is, why are they closing/interrupting the connection?

**Comment by TheDekuTree** [comment]
My guess is that they figured out somehow that we aren't a web browser and are cutting our connection. I'm gonna try:
https://github.com/assaf/zombie
