### ISSUE TITLE
Interesting URL

### ISSUE THREAD

**Issue by nlaha** [ajmwagar/powerschool_gradecheck#5]
https://ps.seattleschools.org/pearson-rest/services/PublicPortalServiceJSON?wsdl
username: pearson
password: m0bApP5

**Comment by nlaha** [comment]
found in:
https://www.npmjs.com/package/powerschool-api

**Comment by ajmwagar** [comment]
Read only. :frowning:

**Comment by nlaha** [comment]
I don't believe so, this is what the powerschool-api npm package uses to get grades, maybe its only read only for seattle school district but why wouldn't they just set a password for it instead?
